/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ASUS
 */
public class HomeFrm extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrm
     */
    public HomeFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnthemvdv = new javax.swing.JButton();
        btnthemsan = new javax.swing.JButton();
        btnthemdoi = new javax.swing.JButton();
        btndkidon = new javax.swing.JButton();
        btndkidoi = new javax.swing.JButton();
        btnthemtran = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ GIẢI CẦU LÔNG");

        btnthemvdv.setText("THÊM VẬN ĐỘNG VIÊN");
        btnthemvdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemvdvActionPerformed(evt);
            }
        });

        btnthemsan.setText("THÊM SÂN ĐẤU");
        btnthemsan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemsanActionPerformed(evt);
            }
        });

        btnthemdoi.setText("THÊM ĐỘI");
        btnthemdoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemdoiActionPerformed(evt);
            }
        });

        btndkidon.setText("ĐĂNG KÍ THI ĐẤU ĐƠN");
        btndkidon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndkidonActionPerformed(evt);
            }
        });

        btndkidoi.setText("ĐĂNG KÍ THI ĐẤU ĐÔI");
        btndkidoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndkidoiActionPerformed(evt);
            }
        });

        btnthemtran.setBackground(new java.awt.Color(255, 0, 0));
        btnthemtran.setText("THÊM TRẬN ĐẤU");
        btnthemtran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemtranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnthemvdv, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnthemsan, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnthemdoi, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btndkidon, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(btndkidoi, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnthemtran, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnthemvdv, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnthemsan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnthemdoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndkidon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndkidoi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(btnthemtran, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemvdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemvdvActionPerformed
            AddVDVFrm vdvfrm = new AddVDVFrm();
            vdvfrm.setVisible(true);
            
        
            // TODO add your handling code here:
    }//GEN-LAST:event_btnthemvdvActionPerformed

    private void btnthemsanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemsanActionPerformed
            AddSanFrm addsan = new AddSanFrm();
            addsan.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnthemsanActionPerformed

    private void btnthemdoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemdoiActionPerformed
            AddDoiFrm adddoi = new AddDoiFrm();
            adddoi.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnthemdoiActionPerformed

    private void btnthemtranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemtranActionPerformed
            ThemTranDauFrm addtran = new ThemTranDauFrm();
            addtran.setVisible(true);
            // TODO add your handling code here:
    }//GEN-LAST:event_btnthemtranActionPerformed

    private void btndkidoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndkidoiActionPerformed
        DangKyThiDauDoiFrm dkidoi = new DangKyThiDauDoiFrm();
        dkidoi.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btndkidoiActionPerformed

    private void btndkidonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndkidonActionPerformed
        DangKyThiDauDonFrm dkidon = new DangKyThiDauDonFrm();
        dkidon.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btndkidonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndkidoi;
    private javax.swing.JButton btndkidon;
    private javax.swing.JButton btnthemdoi;
    private javax.swing.JButton btnthemsan;
    private javax.swing.JButton btnthemtran;
    private javax.swing.JButton btnthemvdv;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
